services:

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: marveldb
      POSTGRES_USER: marveldbuser
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

  credit-card-payment-api:
    build: payment-service
    container_name: credit-card-payment-api
    ports:
      - "9090:9090"
    restart: unless-stopped
